CREATE DATABASE apuestas_d;
USE apuestas_d;
CREATE TABLE USUARIO (
ID_Usuario INT AUTO_INCREMENT NOT NULL,
Nombre VARCHAR(20) NOT NULL, 
Apellido VARCHAR(20) NOT NULL,
Email VARCHAR(20) NOT NULL UNIQUE, 
Numero_telefono VARCHAR(20) NOT NULL, 
Direccion VARCHAR(100) NOT NULL, 
Fecha_registro DATE NOT NULL DEFAULT (CURRENT_DATE),
Estado_KYC ENUM('PENDIENTE','VERIFICADO','RECHAZADO')
		   NOT NULL DEFAULT 'PENDIENTE',
CONSTRAINT PK_Usuario PRIMARY KEY (ID_Usuario)
);


ALTER TABLE USUARIO 
MODIFY Email VARCHAR(100) NOT NULL UNIQUE;

ALTER TABLE USUARIO 
ADD COLUMN Genero ENUM('MASCULINO', 'FEMENINO', 'OTRO', 'NO_ESPECIFICADO') 
NOT NULL DEFAULT 'NO_ESPECIFICADO';

ALTER TABLE USUARIO 
MODIFY Ciudad VARCHAR(50) NOT NULL;

ALTER TABLE USUARIO
MODIFY Fecha_nacimiento DATE NOT NULL;

CREATE TABLE SALDO_CUENTA (
ID_Saldo_cuenta INT NOT NULL AUTO_INCREMENT, 
ID_Usuario INT NOT NULL UNIQUE, 
Saldo_disponible FLOAT(15,2) NOT NULL DEFAULT 0.00,
	CONSTRAINT PK_Saldo_cuenta PRIMARY KEY (ID_Saldo_cuenta), 
    FOREIGN KEY (ID_Usuario) REFERENCES USUARIO (ID_Usuario)
    ON DELETE CASCADE ON UPDATE CASCADE
    );

CREATE TABLE METODO_PAGO (
ID_Metodo_pago INT NOT NULL AUTO_INCREMENT,
ID_Usuario INT NOT NULL UNIQUE, 
Tipo_pago  ENUM("TARJETA_CREDITO", "TARJETA_DEBITO", "TRANSFERENCIA",
						"BILLETERA_DIGITAL", "CONSIGNACION_BANCARIA") NOT NULL,
	CONSTRAINT PK_ID_Metodo_pago PRIMARY KEY (ID_Metodo_pago),
	FOREIGN KEY (ID_Usuario) REFERENCES USUARIO(ID_Usuario)
	ON DELETE CASCADE ON UPDATE CASCADE );
    
ALTER TABLE METODO_PAGO 
MODIFY Tipo_pago ENUM('TARJETA_CREDITO', 'TARJETA_DEBITO', 
                      'TRANSFERENCIA', 'BILLETERA_DIGITAL', 
                      'CONSIGNACION_BANCARIA') NOT NULL;

CREATE TABLE PARTICIPANTES (
ID_Participantes INT AUTO_INCREMENT NOT NULL,
Nombre VARCHAR(20) NOT NULL, 
Tipo ENUM ("EQUIPO", "DEPORTISTA", "OTRO") NOT NULL,
	CONSTRAINT PK_Participantes PRIMARY KEY (ID_Participantes)
    );
    
CREATE TABLE EVENTO (
ID_Evento INT AUTO_INCREMENT NOT NULL, 
Deporte VARCHAR(50) NOT NULL,
Tipo_Evento ENUM ("PARTIDO", "TORNEO", "CARRERA", "COMBATE", "OTRO") NOT NULL,
Fecha DATE NOT NULL,
Liga_torneo VARCHAR(50),
Resultado VARCHAR(50), 
	CONSTRAINT PK_ID_Evento PRIMARY KEY (ID_Evento)
    );
    
CREATE TABLE MERCADO (
ID_Mercado INT AUTO_INCREMENT NOT NULL, 
ID_Evento INT NOT NULL, 
Tipo_mercado ENUM ("GANADOR", "TOTAL_ANOTACIONES", "HANDICAP", "AMBOS_ANOTAN",
					"RESULTADO_EXACTO", "OTRO") NOT NULL, 
Cuota_actual FLOAT (8,2) NOT NULL, 
	CONSTRAINT PK_ID_Mercado PRIMARY KEY (ID_Mercado),
    FOREIGN KEY (ID_Evento) REFERENCES EVENTO(ID_Evento)
    ON DELETE CASCADE ON UPDATE CASCADE );

CREATE TABLE APUESTA (
ID_Apuesta INT AUTO_INCREMENT NOT NULL,
ID_Usuario INT NOT NULL,
ID_Evento INT NOT NULL,
ID_Mercado INT NOT NULL, 
Valor_apostado FLOAT(15,2) NOT NULL CHECK (Valor_apostado > 0), 
	CONSTRAINT PK_ID_Apuesta PRIMARY KEY (ID_Apuesta),
    FOREIGN KEY (ID_Usuario) REFERENCES USUARIO (ID_Usuario),
    FOREIGN KEY (ID_Evento) REFERENCES EVENTO (ID_Evento), 
    FOREIGN KEY (ID_Mercado) REFERENCES MERCADO (ID_Mercado)
    );
    
# ACTUALIZACIÓN TABLA APUESTA

ALTER TABLE APUESTA 
ADD Estado ENUM ('PENDIENTE','GANADA','PERDIDA','ANULADA') NOT NULL;

ALTER TABLE APUESTA
ADD COLUMN ID_Participantes INT NULL,
ADD COLUMN Fecha_hora DATETIME NULL,
ADD COLUMN Ciudad VARCHAR(50) NULL,
ADD FOREIGN KEY (ID_Participantes) REFERENCES PARTICIPANTES(ID_Participantes);

CREATE TABLE CUOTA (
ID_Cuota INT AUTO_INCREMENT NOT NULL,
ID_Mercado INT NOT NULL, 
ID_Apuesta INT NOT NULL, 
Valor_cuota FLOAT(8,2) NOT NULL,
	CONSTRAINT PK_ID_Cuota PRIMARY KEY (ID_Cuota),
    FOREIGN KEY (ID_Mercado) REFERENCES MERCADO(ID_Mercado), 
    FOREIGN KEY (ID_Apuesta) REFERENCES APUESTA (ID_Apuesta)
    ON DELETE CASCADE
    );
    
CREATE TABLE HISTORIAL_CUOTA (
ID_Historial_cuota INT AUTO_INCREMENT NOT NULL,
ID_Cuota INT NOT NULL, 
Cuota_anterior FLOAT (8,2) NOT NULL, 
Cuota_nueva FLOAT (8,2) NOT NULL, 
Fecha DATE NOT NULL, 
Hora TIME NOT NULL, 
	CONSTRAINT PK_ID_Historial_cuota PRIMARY KEY (ID_Historial_cuota),
    FOREIGN KEY (ID_Cuota) REFERENCES CUOTA (ID_Cuota)
    ON DELETE CASCADE
);
    
CREATE TABLE TRANSACCION (
ID_Transaccion INT AUTO_INCREMENT NOT NULL, 
ID_Usuario INT NOT NULL, 
ID_Apuesta INT NOT NULL, 
ID_Metodo_pago INT NOT NULL, 
Tipo_transaccion ENUM ("DEPOSITO", "RETIRO", "APUESTA", "GANANCIA", "AJUSTE") NOT NULL,
Fecha DATE NOT NULL, 
Hora TIME NOT NULL, 
Valor FLOAT (15,2), 
	CONSTRAINT PK_ID_Transaccion PRIMARY KEY (ID_Transaccion),
    FOREIGN KEY (ID_Usuario) REFERENCES USUARIO (ID_Usuario),
    FOREIGN KEY (ID_Apuesta) REFERENCES APUESTA (ID_Apuesta), 
    FOREIGN KEY (ID_Metodo_pago) REFERENCES METODO_PAGO (ID_Metodo_pago)
    );
    
ALTER TABLE TRANSACCION 
MODIFY ID_Apuesta INT NULL;

CREATE TABLE HISTORIAL_APUESTA (
ID_Historial_apuesta INT AUTO_INCREMENT NOT NULL, 
ID_Usuario  INT NOT NULL,
ID_Apuesta  INT NOT NULL,
ID_Evento   INT NOT NULL,
ID_Mercado  INT NOT NULL,
	 CONSTRAINT PK_Historial_apuesta PRIMARY KEY (ID_Historial_apuesta),
     FOREIGN KEY (ID_Usuario) REFERENCES USUARIO (ID_Usuario),
     FOREIGN KEY (ID_Apuesta) REFERENCES APUESTA (ID_Apuesta),
     FOREIGN KEY (ID_Evento) REFERENCES EVENTO (ID_Evento),
     FOREIGN KEY (ID_Mercado) REFERENCES MERCADO (ID_Mercado)
     );

CREATE TABLE PARTICIPANTE_EVENTO (
ID_Participante_evento  INT NOT NULL,
ID_Evento   INT NOT NULL,
ID_Mercado  INT NOT NULL, 
	CONSTRAINT PK_ID_Participante_evento PRIMARY KEY (ID_Participante_evento),
    FOREIGN KEY (ID_Evento) REFERENCES EVENTO (ID_Evento),
    FOREIGN KEY (ID_Mercado) REFERENCES MERCADO (ID_Mercado)
    );

ALTER TABLE PARTICIPANTE_EVENTO 
MODIFY ID_Participante_evento INT NOT NULL AUTO_INCREMENT;

ALTER TABLE PARTICIPANTE_EVENTO
ADD COLUMN ID_Participantes INT NOT NULL,
ADD FOREIGN KEY (ID_Participantes) REFERENCES PARTICIPANTES(ID_Participantes);

## INDICES 

## CONSULTAS USUARIO
CREATE INDEX idx_apuesta_usuario ON APUESTA(ID_Usuario);
CREATE INDEX idx_transaccion_usuario ON TRANSACCION(ID_Usuario);

## EVENTOS POR FECHA
CREATE INDEX idx_evento_fecha ON EVENTO(Fecha, Deporte);

## MERCADOS POR EVENTO
CREATE INDEX idx_mercado_evento ON MERCADO(ID_Evento);

## HISTORIAL CUOTAS POR TIEMPO
CREATE INDEX idx_histcuota_fecha ON HISTORIAL_CUOTA(ID_Cuota, Fecha, Hora);

## ESTADO DE APUESTAS (APUESTAS PENDIENTES)
CREATE INDEX idx_apuesta_estado ON APUESTA(Estado);

## TRIGGERS DE INTEGRIDAD

# REGISTRO AUTOMÁTICO HISTORIAL_APUESTAS
DELIMITER $$
CREATE TRIGGER trg_after_apuesta_insert
AFTER INSERT ON APUESTA
FOR EACH ROW
BEGIN
    INSERT INTO HISTORIAL_APUESTA
        (ID_Usuario, ID_Apuesta, ID_Evento, ID_Mercado)
    VALUES
        (NEW.ID_Usuario, NEW.ID_Apuesta,
         NEW.ID_Evento, NEW.ID_Mercado);
END$$
DELIMITER ;

# ACTUALIZACIÓN DE SALDO EN REGISTRO DE TRANSACCIÓN
DROP TRIGGER IF EXISTS trg_actualizar_saldo;

DELIMITER $$
CREATE TRIGGER trg_actualizar_saldo
AFTER INSERT ON TRANSACCION
FOR EACH ROW
BEGIN
    IF NEW.Tipo_transaccion IN ('DEPOSITO', 'GANANCIA') THEN
        UPDATE SALDO_CUENTA
        SET Saldo_disponible = Saldo_disponible + NEW.Valor
        WHERE ID_Usuario = NEW.ID_Usuario;
    ELSEIF NEW.Tipo_transaccion IN ('RETIRO', 'APUESTA') THEN
        UPDATE SALDO_CUENTA
        SET Saldo_disponible = GREATEST(0, Saldo_disponible - NEW.Valor)
        WHERE ID_Usuario = NEW.ID_Usuario;
    ELSEIF NEW.Tipo_transaccion = 'AJUSTE' THEN
        UPDATE SALDO_CUENTA
        SET Saldo_disponible = GREATEST(0, Saldo_disponible + NEW.Valor)
        WHERE ID_Usuario = NEW.ID_Usuario;
    END IF;
END$$
DELIMITER ;

DROP TRIGGER IF EXISTS trg_after_apuesta_insert;

SHOW TABLES; 

SHOW COLUMNS FROM METODO_PAGO LIKE 'Tipo_pago';


USE apuestas_d;
SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE HISTORIAL_CUOTA;
TRUNCATE TABLE HISTORIAL_APUESTA;
TRUNCATE TABLE TRANSACCION;
TRUNCATE TABLE CUOTA;
TRUNCATE TABLE APUESTA;
TRUNCATE TABLE PARTICIPANTE_EVENTO;
TRUNCATE TABLE MERCADO;
TRUNCATE TABLE EVENTO;
TRUNCATE TABLE PARTICIPANTES;
TRUNCATE TABLE METODO_PAGO;
TRUNCATE TABLE SALDO_CUENTA;
TRUNCATE TABLE USUARIO;

SET FOREIGN_KEY_CHECKS = 1;
